/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lexico;

/**
 * @author brunoslima
 * @author leandroungari
 */
public enum Simbolo {
    
    PALAVRA_RESERVADA_PROGRAM,
    PALAVRA_RESERVADA_BEGIN,
    PALAVRA_RESERVADA_END,
    PALAVRA_RESERVADA_PROCEDURE,
    PALAVRA_RESERVADA_VAR,
    VALOR_LOGICO_TRUE,
    VALOR_LOGICO_FALSE,
    TIPO_INTEIRO,
    TIPO_REAL,
    TIPO_BOOLEANO,
    PALAVRA_RESERVADA_READ,
    PALAVRA_RESERVADA_WRITE,
    SIMBOLO_DOIS_PONTOS,
    SIMBOLO_PONTO_VIRGULA,
    SIMBOLO_VIRGULA,
    SIMBOLO_PONTO,
    ESTRUTURA_CONDICAO_IF,
    ESTRUTURA_CONDICAO_THEN,
    ESTRUTURA_CONDICAO_ELSE,
    ESTRUTURA_REPETICAO_WHILE,
    ESTRUTURA_REPETICAO_DO,
    SIMBOLO_IGUAL,
    SIMBOLO_DIFERENTE,
    SIMBOLO_MENOR,
    SIMBOLO_MENOR_IGUAL,
    SIMBOLO_MAIOR,
    SIMBOLO_MAIOR_IGUAL,
    OPERADOR_ATRIBUICAO,
    OPERADOR_ADICAO,
    OPERADOR_SUBTRACAO,
    OPERADOR_MULTIPLICACAO,
    OPERADOR_DIVISAO,
    OPERADOR_AND,
    OPERADOR_OR,
    OPERADOR_NOT,
    PARENTESES_ABRE,
    PARENTESES_FECHA,
    NUMERO_INTEIRO,
    IDENTIFICADOR,
    ERROR,
    
}
