/* Grammar.java */
/* Generated By:JavaCC: Do not edit this line. Grammar.java */
package sintatico;

public class Grammar implements GrammarConstants {

static void error_skipto(int kind) {
  ParseException e = generateParseException();  // generate the exception object.
  System.out.println(e.toString());  // print the error message
  Token t;
  do {
    t = getNextToken();
  } while (t.kind != kind);
    // The above loop consumes tokens all the way up to a token of
    // "kind".  We use a do-while loop rather than a while because the
    // current token is the one immediately before the erroneous token
    // (in our case the token immediately before what should have been
    // "if"/"while".
}

static void showMessageError(int line, int column, String message, String descricao){

    System.out.println(
        message + "\u005cn" +
        "Linha: " + line + " Coluna: " + column + "\u005cn" +
        descricao
    );
}

  static final public void compilationUnit() throws ParseException {
    programDeclaration();
    jj_consume_token(0);
  }

  static final public void programDeclaration() throws ParseException {
    try {
      jj_consume_token(PROGRAM);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Palavra reservada program esperada", "Descri\u00e7\u00e3o");
        //error_skipto(IDENTIFICADOR);

    }
    try {
      jj_consume_token(IDENTIFICADOR);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Identificador de programa faltando", "Descri\u00e7\u00e3o");
    }
    try {
      jj_consume_token(PONTO_VIRGULA);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto e v\u00edrgula faltando", "Descri\u00e7\u00e3o");
    }
    bloco();
    try {
      jj_consume_token(PONTO);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto final faltando", "Descri\u00e7\u00e3o");
    }
  }

  static final public void bloco() throws ParseException {
    if (jj_2_1(2)) {
      parteDeclaracaoVariaveis();
    } else {
      ;
    }
    label_1:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_1;
      }
      parteDeclaracaoSubRotinas();
      try {
        jj_consume_token(PONTO_VIRGULA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto e v\u00edrgula faltando", "Descri\u00e7\u00e3o");
      }
    }
    comandoComposto();
  }

  static final public void parteDeclaracaoVariaveis() throws ParseException {
    declaracaoVariaveis();
    label_2:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_2;
      }
      try {
        jj_consume_token(PONTO_VIRGULA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto e v\u00edrgula faltando", "Descri\u00e7\u00e3o");
      }
      declaracaoVariaveis();
    }
    try {
      jj_consume_token(PONTO_VIRGULA);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto e v\u00edrgula faltando", "Descri\u00e7\u00e3o");
    }
  }

  static final public void declaracaoVariaveis() throws ParseException {
    tipo();
    listaIdentificadores();
  }

  static final public void listaIdentificadores() throws ParseException {
    variavel();
    label_3:
    while (true) {
      if (jj_2_4(2)) {
        ;
      } else {
        break label_3;
      }
      try {
        jj_consume_token(VIRGULA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "V\u00edrgula faltando", "Descri\u00e7\u00e3o");
      }
      variavel();
    }
  }

  static final public void parteDeclaracaoSubRotinas() throws ParseException {
    try {
      jj_consume_token(PROCEDURE);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Palavra reservada procedure esperada", "Descri\u00e7\u00e3o");
    }
    try {
      jj_consume_token(IDENTIFICADOR);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Identificador de procedure esperado", "Descri\u00e7\u00e3o");
    }
    declaracaoProcedimentos();
  }

  static final public void declaracaoProcedimentos() throws ParseException {
    if (jj_2_5(2)) {
      try {
        jj_consume_token(PARENTESES_ABRE);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Abre parentese faltando", "Descri\u00e7\u00e3o");
      }
      parametrosFormais();
      try {
        jj_consume_token(PARENTESES_FECHA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Fecha parenteses faltando", "Descri\u00e7\u00e3o");
      }
    } else {
      ;
    }
    try {
      jj_consume_token(PONTO_VIRGULA);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto e v\u00edrgula faltando", "Descri\u00e7\u00e3o");
    }
    bloco();
  }

  static final public void parametrosFormais() throws ParseException {
    secaoParametrosFormais();
    label_4:
    while (true) {
      if (jj_2_6(2)) {
        ;
      } else {
        break label_4;
      }
      try {
        jj_consume_token(PONTO_VIRGULA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto e v\u00edrgula faltando", "Descri\u00e7\u00e3o");
      }
      secaoParametrosFormais();
    }
  }

  static final public void secaoParametrosFormais() throws ParseException {
    if (jj_2_7(2)) {
      try {
        jj_consume_token(VAR);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Palavra reservada var esperada", "Descri\u00e7\u00e3o");
      }
    } else {
      ;
    }
    listaIdentificadores();
    try {
      jj_consume_token(DOIS_PONTOS);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Dois pontos faltando", "Descri\u00e7\u00e3o");
    }
    tipo();
  }

  static final public void tipo() throws ParseException {
    try {
      if (jj_2_8(2)) {
        jj_consume_token(INT);
      } else if (jj_2_9(2)) {
        jj_consume_token(BOOLEAN);
      } else if (jj_2_10(2)) {
        jj_consume_token(REAL);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Identificador de tipo esperado", "Descri\u00e7\u00e3o");
    }
  }

  static final public void comandoComposto() throws ParseException {
    try {
      jj_consume_token(BEGIN);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Palavra reservada begin esperada", "Descri\u00e7\u00e3o");
    }
    comando();
    label_5:
    while (true) {
      if (jj_2_11(2)) {
        ;
      } else {
        break label_5;
      }
      try {
        jj_consume_token(PONTO_VIRGULA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Ponto e v\u00edrgula faltando", "Descri\u00e7\u00e3o");
      }
      comando();
    }
    try {
      jj_consume_token(END);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Palavra reservada end esperada", "Descri\u00e7\u00e3o");
    }
  }

  static final public void comando() throws ParseException {
    if (jj_2_12(2)) {
      atribuicao();
    } else if (jj_2_13(2)) {
      chamadaProcedimento();
    } else if (jj_2_14(2)) {
      comandoComposto();
    } else if (jj_2_15(2)) {
      comandoCondicional();
    } else if (jj_2_16(2)) {
      comandoRepetitivo();
    } else if (jj_2_17(2)) {
      try {
        jj_consume_token(READ);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Palavra reservada read esperada", "Descri\u00e7\u00e3o");
      }
      try {
        jj_consume_token(PARENTESES_ABRE);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Abre parenteses esperado", "Descri\u00e7\u00e3o");
      }
      listaIdentificadores();
      try {
        jj_consume_token(PARENTESES_FECHA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Fecha parenteses esperado", "Descri\u00e7\u00e3o");
      }
    } else if (jj_2_18(2)) {
      try {
        jj_consume_token(WRITE);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Palavra reservada write esperada", "Descri\u00e7\u00e3o");
      }
      try {
        jj_consume_token(PARENTESES_ABRE);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Abre parenteses esperado", "Descri\u00e7\u00e3o");
      }
      listaIdentificadores();
      try {
        jj_consume_token(PARENTESES_FECHA);
      } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Fecha parenteses esperado", "Descri\u00e7\u00e3o");
      }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void atribuicao() throws ParseException {
    variavel();
    try {
      jj_consume_token(OP_ATRIBUICAO);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Operador de atribui\u00e7\u00e3o esperado", "Descri\u00e7\u00e3o");
    }
    expressao();
  }

  static final public void chamadaProcedimento() throws ParseException {
    try {
      jj_consume_token(IDENTIFICADOR);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Identificador de procedimento esperado", "Descri\u00e7\u00e3o");
    }
    try {
      jj_consume_token(PARENTESES_ABRE);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Abre parenteses esperado", "Descri\u00e7\u00e3o");
    }
    listaExpressoes();
    try {
      jj_consume_token(PARENTESES_FECHA);
    } catch (ParseException e) {
showMessageError(e.currentToken.next.beginLine, e.currentToken.next.beginColumn, "Fecha parenteses esperado", "Descri\u00e7\u00e3o");
    }
  }

  static final public void comandoCondicional() throws ParseException {
    jj_consume_token(IF);
    expressao();
    jj_consume_token(THEN);
    comando();
    if (jj_2_19(2)) {
      jj_consume_token(ELSE);
      comando();
    } else {
      ;
    }
  }

  static final public void comandoRepetitivo() throws ParseException {
    jj_consume_token(WHILE);
    expressao();
    jj_consume_token(DO);
    comando();
  }

  static final public void expressao() throws ParseException {
    expressaoSimples();
    if (jj_2_20(2)) {
      relacao();
      expressaoSimples();
    } else {
      ;
    }
  }

  static final public void expressaoSimples() throws ParseException {
    if (jj_2_23(2)) {
      if (jj_2_21(2)) {
        jj_consume_token(OP_ADICAO);
      } else if (jj_2_22(2)) {
        jj_consume_token(OP_SUBTRACAO);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } else {
      ;
    }
    termo();
    label_6:
    while (true) {
      if (jj_2_24(2)) {
        ;
      } else {
        break label_6;
      }
      if (jj_2_25(2)) {
        jj_consume_token(OP_ADICAO);
      } else if (jj_2_26(2)) {
        jj_consume_token(OP_SUBTRACAO);
      } else if (jj_2_27(2)) {
        jj_consume_token(OP_OR);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      termo();
    }
  }

  static final public void relacao() throws ParseException {
    if (jj_2_28(2)) {
      jj_consume_token(SIMBOLO_IGUAL);
    } else if (jj_2_29(2)) {
      jj_consume_token(SIMBOLO_DIFERENTE);
    } else if (jj_2_30(2)) {
      jj_consume_token(SIMBOLO_MENOR);
    } else if (jj_2_31(2)) {
      jj_consume_token(SIMBOLO_MENOR_IGUAL);
    } else if (jj_2_32(2)) {
      jj_consume_token(SIMBOLO_MAIOR_IGUAL);
    } else if (jj_2_33(2)) {
      jj_consume_token(SIMBOLO_MAIOR);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void termo() throws ParseException {
    fator();
    label_7:
    while (true) {
      if (jj_2_34(2)) {
        ;
      } else {
        break label_7;
      }
      if (jj_2_35(2)) {
        jj_consume_token(OP_MULTIPLICACAO);
      } else if (jj_2_36(2)) {
        jj_consume_token(OP_DIVISAO);
      } else if (jj_2_37(2)) {
        jj_consume_token(OP_AND);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      fator();
    }
  }

  static final public void fator() throws ParseException {
    if (jj_2_38(2)) {
      variavel();
    } else if (jj_2_39(2)) {
      jj_consume_token(NUMERO_INTEIRO);
    } else if (jj_2_40(2)) {
      jj_consume_token(NUMERO_REAL);
    } else if (jj_2_41(2)) {
      jj_consume_token(PARENTESES_ABRE);
      expressao();
      jj_consume_token(PARENTESES_FECHA);
    } else if (jj_2_42(2)) {
      jj_consume_token(OP_NOT);
      fator();
    } else if (jj_2_43(2)) {
      jj_consume_token(TRUE);
    } else if (jj_2_44(2)) {
      jj_consume_token(FALSE);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void listaExpressoes() throws ParseException {
    expressao();
    label_8:
    while (true) {
      if (jj_2_45(2)) {
        ;
      } else {
        break label_8;
      }
      jj_consume_token(VIRGULA);
      expressao();
    }
  }

  static final public void variavel() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
  }

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_2_29(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  static private boolean jj_2_30(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  static private boolean jj_2_31(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  static private boolean jj_2_32(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  static private boolean jj_2_33(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  static private boolean jj_2_34(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  static private boolean jj_2_35(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  static private boolean jj_2_36(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  static private boolean jj_2_37(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  static private boolean jj_2_38(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  static private boolean jj_2_39(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  static private boolean jj_2_40(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  static private boolean jj_2_41(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  static private boolean jj_2_42(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  static private boolean jj_2_43(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  static private boolean jj_2_44(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_44(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  static private boolean jj_2_45(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_45(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  static private boolean jj_3_16()
 {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3_15()
 {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(PONTO_VIRGULA)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_12()
 {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3_14()
 {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3_37()
 {
    if (jj_scan_token(OP_AND)) return true;
    return false;
  }

  static private boolean jj_3_13()
 {
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_14()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_12()
 {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3_26()
 {
    if (jj_scan_token(OP_SUBTRACAO)) return true;
    return false;
  }

  static private boolean jj_3R_9()
 {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_16()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(PARENTESES_ABRE)) return true;
    return false;
  }

  static private boolean jj_3_30()
 {
    if (jj_scan_token(SIMBOLO_MENOR)) return true;
    return false;
  }

  static private boolean jj_3_45()
 {
    if (jj_scan_token(VIRGULA)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3_36()
 {
    if (jj_scan_token(OP_DIVISAO)) return true;
    return false;
  }

  static private boolean jj_3_11()
 {
    if (jj_scan_token(PONTO_VIRGULA)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_scan_token(PARENTESES_ABRE)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3_25()
 {
    if (jj_scan_token(OP_ADICAO)) return true;
    return false;
  }

  static private boolean jj_3_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) {
    jj_scanpos = xsp;
    if (jj_3_27()) return true;
    }
    }
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_15()
 {
    if (jj_scan_token(40)) return true;
    if (jj_scan_token(OP_ATRIBUICAO)) return true;
    return false;
  }

  static private boolean jj_3_44()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3_29()
 {
    if (jj_scan_token(SIMBOLO_DIFERENTE)) return true;
    return false;
  }

  static private boolean jj_3_43()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3_42()
 {
    if (jj_scan_token(OP_NOT)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3R_17()
 {
    if (jj_scan_token(BEGIN)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3_41()
 {
    if (jj_scan_token(PARENTESES_ABRE)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3_35()
 {
    if (jj_scan_token(OP_MULTIPLICACAO)) return true;
    return false;
  }

  static private boolean jj_3_40()
 {
    if (jj_scan_token(NUMERO_REAL)) return true;
    return false;
  }

  static private boolean jj_3_34()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_35()) {
    jj_scanpos = xsp;
    if (jj_3_36()) {
    jj_scanpos = xsp;
    if (jj_3_37()) return true;
    }
    }
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_39()
 {
    if (jj_scan_token(NUMERO_INTEIRO)) return true;
    return false;
  }

  static private boolean jj_3R_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_38()) {
    jj_scanpos = xsp;
    if (jj_3_39()) {
    jj_scanpos = xsp;
    if (jj_3_40()) {
    jj_scanpos = xsp;
    if (jj_3_41()) {
    jj_scanpos = xsp;
    if (jj_3_42()) {
    jj_scanpos = xsp;
    if (jj_3_43()) {
    jj_scanpos = xsp;
    if (jj_3_44()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_38()
 {
    if (jj_scan_token(40)) return true;
    return false;
  }

  static private boolean jj_3_33()
 {
    if (jj_scan_token(SIMBOLO_MAIOR)) return true;
    return false;
  }

  static private boolean jj_3_19()
 {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_scan_token(REAL)) return true;
    return false;
  }

  static private boolean jj_3_20()
 {
    if (jj_3R_20()) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_22()
 {
    if (jj_scan_token(OP_SUBTRACAO)) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_22()
 {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3_28()
 {
    if (jj_scan_token(SIMBOLO_IGUAL)) return true;
    return false;
  }

  static private boolean jj_3R_25()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_28()) {
    jj_scanpos = xsp;
    if (jj_3_29()) {
    jj_scanpos = xsp;
    if (jj_3_30()) {
    jj_scanpos = xsp;
    if (jj_3_31()) {
    jj_scanpos = xsp;
    if (jj_3_32()) {
    jj_scanpos = xsp;
    if (jj_3_33()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_10()
 {
    if (jj_scan_token(PROCEDURE)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3_21()
 {
    if (jj_scan_token(OP_ADICAO)) return true;
    return false;
  }

  static private boolean jj_3_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) return true;
    }
    return false;
  }

  static private boolean jj_3R_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_23()) jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(VIRGULA)) return true;
    if (jj_scan_token(40)) return true;
    return false;
  }

  static private boolean jj_3_18()
 {
    if (jj_scan_token(WRITE)) return true;
    if (jj_scan_token(PARENTESES_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_24()
 {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_32()
 {
    if (jj_scan_token(SIMBOLO_MAIOR_IGUAL)) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_scan_token(VAR)) return true;
    return false;
  }

  static private boolean jj_3R_19()
 {
    if (jj_scan_token(WHILE)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_26()
 {
    if (jj_scan_token(40)) return true;
    return false;
  }

  static private boolean jj_3R_18()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) jj_scanpos = xsp;
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_11()
 {
    if (jj_3R_25()) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3_27()
 {
    if (jj_scan_token(OP_OR)) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_scan_token(PONTO_VIRGULA)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3_17()
 {
    if (jj_scan_token(READ)) return true;
    if (jj_scan_token(PARENTESES_ABRE)) return true;
    return false;
  }

  static private boolean jj_3_31()
 {
    if (jj_scan_token(SIMBOLO_MENOR_IGUAL)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public GrammarTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[45];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Grammar(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Grammar(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Grammar(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Grammar(GrammarTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[47];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 47; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 45; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
            case 43: jj_3_44(); break;
            case 44: jj_3_45(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
